[package]
name = "aws-arn"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
description = "Provides types, builders, and other helpers to manipulate AWS Amazon Resource Name (ARN) strings"
documentation = "https://docs.rs/aws-arn/"
repository = "https://github.com/johnstonskj/rust-aws-arn.git"
license = "MIT"
readme = "README.md"
publish = true

#[features]
#service_validation = ["toml"]

[dependencies]
lazy_static = "1.4.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"