name: Rust

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Docs
      run: cargo doc --no-deps
